runBootScreen('github', [
  'RETRO TERMINAL OS v2.6 [AMBER BUILD]',
  'INITIALIZING GITHUB INTERFACE...',
  'LOADING REPOSITORY INDEX...',
  'MOUNTING CODE FILESYSTEM...',
  'ESTABLISHING SSH TUNNEL...',
  'ALL SYSTEMS NOMINAL. WELCOME, OPERATOR.'
]);
